import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import BreadCrumbs from "@/components/breadCrumbs/BreadCrumbs";

// Load fonts
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import { Poppins } from 'next/font/google';
import { Radley } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const radley = Radley({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-radley',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${radley.variable} ${geistSans.variable}`}>
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <BreadCrumbs />
        {children}
        <Footer />
      </body>
    </html>
  );
}
