<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./global.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
=======
import { Inter } from "next/font/google";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer"; // ✅ Make sure this is correct
import BreadCrumbs from "@/components/breadCrumbs/BreadCrumbs";
const inter = Inter({
  variable: "--font-sans",
>>>>>>> fcf1a3c0ebbdf2e63ede61e459d13844da394ff0
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <BreadCrumbs/>
        {children}
        <Footer /> {/* ✅ Make sure this is self-closing */}
>>>>>>> fcf1a3c0ebbdf2e63ede61e459d13844da394ff0
      </body>
    </html>
  );
}
