import { Inter } from "next/font/google";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer"; // ✅ Make sure this is correct
import BreadCrumbs from "@/components/breadCrumbs/BreadCrumbs";
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <BreadCrumbs/>
        {children}
        <Footer /> {/* ✅ Make sure this is self-closing */}
      </body>
    </html>
  );
}
